[webserver]
port = ":8081"

# register data providers
[[providers]]
name = "turplanering"
type = "mvt_postgis"
host = "db"
port = 5432
database = "turplanering"
user = "tegola"
password = "password"
srid = 3857

    [[providers.layers]]
    name = "trail_sections"
    geometry_type = "LineString"
    srid = 3857
    sql = """\
        SELECT ST_AsMVTGeom(geog, !BBOX!) AS geom, sections.id AS gid \
               , (SELECT ST_SetSRID(ST_Extent(geog), 3857) as extent    \
                  FROM trail_sections                                   \
                  WHERE trail_sections.trail_id = sections.trail_id)    \
               , color                                                  \
               , trails.id as trail_id, trails.description, trails.name \

        FROM trail_sections AS sections \
            INNER JOIN trails ON sections.trail_id = trails.id \

        WHERE geog && !BBOX!\
        """

[[maps]]
name = "trails"

    [[maps.layers]]
    name = "trail_sections"
    provider_layer = "turplanering.trail_sections"
