version: '2.0'
services:

  tegola:
    image: gospatial/tegola
    volumes:
    - ./cfg/tegola.toml:/opt/tegola_config/config.toml
    ports:
    - "8081:8081"
    depends_on:
    - "db"
    command: serve --config /opt/tegola_config/config.toml

  db:
    image: postgis/postgis
    environment:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=turplanering
    ports:
    - "5432:5432"
    volumes:
    - dbdata:/var/lib/postgresql/data/
    - ./cfg/init-db.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
    dbdata: {}
