name:                turplanering
version:             0.1.0.0
github:              "EmilGedda/turplanering"
license:             BSD3
author:              "Emil Gedda"
maintainer:          "emil.gedda@emilgedda.se"
copyright:           "2021 Emil Gedda"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/EmilGedda/turplanering#README>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wno-missing-signatures
- -Wno-name-shadowing
- -Wno-type-defaults
- -Wno-partial-type-signatures
- -Wno-unused-do-bind
- -threaded
- -rtsopts
- -with-rtsopts=-N

default-extensions:
- BangPatterns
- BlockArguments
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- EmptyDataDeriving
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- InstanceSigs
- KindSignatures
- MultiParamTypeClasses
- NamedFieldPuns
- PolyKinds
- QualifiedDo
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications


library:
  source-dirs: src
  dependencies:
  - aeson                   ^>= 1.5
  - ansi-terminal           ^>= 0.11
  - attoparsec              ^>= 0.14
  - bytestring              ^>= 0.10
  - containers              ^>= 0.6
  - co-log-core             ^>= 0.3
  - dhall                   ^>= 1.40
  - exceptions              ^>= 0.10
  - genvalidity             ^>= 0.11
  - genvalidity-bytestring  ^>= 0.6
  - geojson                 ^>= 4.0
  - http-client             ^>= 0.7
  - http-client-tls         ^>= 0.3
  - http-types              ^>= 0.12
  - mtl                     ^>= 2.2
  - opaleye                 ^>= 0.7
  - optics                  ^>= 0.4
  - postgresql-simple       ^>= 0.6
  - product-profunctors     ^>= 0.11
  - random                  ^>= 1.2
  - safe-coloured-text      ^>= 0.1
  - servant                 ^>= 0.18
  - servant-server          ^>= 0.18
  - template-haskell        ^>= 2.17
  - text                    ^>= 1.2
  - time                    ^>= 1.9
  - unordered-containers    ^>= 0.2
  - validity                ^>= 0.11
  - validity-bytestring     ^>= 0.4
  - vault                   ^>= 0.3
  - wai                     ^>= 3.2
  - wkt-geom                ^>= 0.0
  - xeno                    ^>= 0.4

executables:
  turplanering:
    main:                Main.hs
    source-dirs:         app/Turplanering
    when:
    - condition: false
      other-modules: Paths_turplanering
    dependencies:
    - turplanering
    - bytestring                    ^>= 0.10
    - co-log-core                   ^>= 0.3
    - containers                    ^>= 0.6
    - dhall                         ^>= 1.40
    - directory                     ^>= 1.3
    - filepath                      ^>= 1.4
    - http-types                    ^>= 0.12
    - mtl                           ^>= 2.2
    - postgresql-simple             ^>= 0.6
    - random                        ^>= 1.2
    - safe-coloured-text-terminfo   ^>= 0.0
    - servant                       ^>= 0.18
    - text                          ^>= 1.2
    - wai                           ^>= 3.2
    - wai-cors                      ^>= 0.2
    - wai-extra                     ^>= 3.1
    - warp                          ^>= 3.3
  turplanering-scrape:
    main:                Main.hs
    source-dirs:         app/Datascraper
    when:
    - condition: false
      other-modules: Paths_turplanering
    dependencies:
    - turplanering
    - aeson                   ^>= 1.5
    - deepseq                 ^>= 1.4
    - http-client             ^>= 0.7
    - http-client-tls         ^>= 0.3
    - containers              ^>= 0.6
    - bytestring              ^>= 0.10
    - streamly                ^>= 0.8
    - timeit                  ^>= 2.0
    - geojson                 ^>= 4.0

  turplanering-prepare-sql:
    main:                Main.hs
    source-dirs:         app/PrepareSQL
    when:
    - condition: false
      other-modules: Paths_turplanering
    dependencies:
    - turplanering
    - aeson                   ^>= 1.5
    - bytestring              ^>= 0.10
    - containers              ^>= 0.6
    - geojson                 ^>= 4.0
    - optics                  ^>= 0.4
    - text                    ^>= 1.2

tests:
  test:
    main:                Spec.hs
    source-dirs:         test
    when:
    - condition: false
      other-modules: Paths_turplanering
    dependencies:
    - turplanering
    - containers            ^>= 0.6
    - genvalidity           ^>= 0.11
    - genvalidity-hspec     ^>= 0.7
    - genvalidity-text      ^>= 0.7
    - hspec                 ^>= 2.8
    - hspec-expectations    ^>= 0.8
    - optics                ^>= 0.4
    - text                  ^>= 1.2
    - validity              ^>= 0.11
    - validity-text         ^>= 0.3
    - QuickCheck            ^>= 2.14
