name:                turplanering
version:             0.1.0.0
github:              "EmilGedda/turplanering"
license:             BSD3
author:              "Emil Gedda"
maintainer:          "emil.gedda@emilgedda.se"
copyright:           "2021 Emil Gedda"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/EmilGedda/turplanering#README>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wno-missing-signatures
- -Wno-name-shadowing
- -Wno-type-defaults
- -Wno-partial-type-signatures

library:
  source-dirs: src
  dependencies:
  - aeson                   ^>= 1.5
  - bytestring              ^>= 0.10
  - containers              ^>= 0.6
  - geojson                 ^>= 4.0
  - http-types              ^>= 0.12
  - microlens               ^>= 0.4
  - microlens-th            ^>= 0.4
  - morpheus-graphql        ^>= 0.16
  - mtl                     ^>= 2.2
  - opaleye                 ^>= 0.7
  - postgresql-simple       ^>= 0.6
  - product-profunctors     ^>= 0.11
  - text                    ^>= 1.2
  - unordered-containers    ^>= 0.2
  - wai                     ^>= 3.2
  - wkt-geom                ^>= 0.0
  - async # ? or lifted-async

executables:
  turplanering:
    main:                Main.hs
    source-dirs:         app
    when:
    - condition: false
      other-modules: Paths_turplanering
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - turplanering
    - morpheus-graphql        ^>= 0.16
    - bytestring              ^>= 0.10
    - http-types              ^>= 0.12
    - wai                     ^>= 3.2
    - warp                    ^>= 3.3

tests:
  test:
    main:                Spec.hs
    source-dirs:         test
    when:
    - condition: false
      other-modules: Paths_turplanering
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - turplanering
