name:                turplanering
version:             0.1.0.0
github:              "EmilGedda/turplanering"
license:             BSD3
author:              "Emil Gedda"
maintainer:          "emil.gedda@emilgedda.se"
copyright:           "2021 Emil Gedda"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/EmilGedda/turplanering#README>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wno-missing-signatures
- -Wno-name-shadowing
- -Wno-type-defaults
- -Wno-partial-type-signatures

library:
  source-dirs: src
  dependencies:
  - aeson                   ^>= 1.5
  - ansi-terminal           ^>= 0.11
  - attoparsec              ^>= 0.13
  - bytestring              ^>= 0.10
  - containers              ^>= 0.6
  - containers              ^>= 0.6
  - dhall                   ^>= 1.39
  - genvalidity             ^>= 0.11
  - genvalidity-bytestring  ^>= 0.6
  - geojson                 ^>= 4.0
  - http-types              ^>= 0.12
  - mtl                     ^>= 2.2
  - opaleye                 ^>= 0.7
  - optics                  ^>= 0.3
  - postgresql-simple       ^>= 0.6
  - product-profunctors     ^>= 0.11
  - random                  ^>= 1.2
  - servant                 ^>= 0.18
  - servant-server          ^>= 0.18
  - text                    ^>= 1.2
  - unordered-containers    ^>= 0.2
  - validity                ^>= 0.11
  - validity-bytestring     ^>= 0.4
  - vault                   ^>= 0.3
  - wai                     ^>= 3.2
  - wkt-geom                ^>= 0.0

executables:
  turplanering:
    main:                Main.hs
    source-dirs:         app
    when:
    - condition: false
      other-modules: Paths_turplanering
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - turplanering
    - dhall                   ^>= 1.39
    - directory               ^>= 1.3
    - filepath                ^>= 1.4
    - mtl                     ^>= 2.2
    - bytestring              ^>= 0.10
    - http-types              ^>= 0.12
    - postgresql-simple       ^>= 0.6
    - random                  ^>= 1.2
    - servant                 ^>= 0.18
    - text                    ^>= 1.2
    - wai                     ^>= 3.2
    - wai-extra               ^>= 3.1
    - warp                    ^>= 3.3

tests:
  test:
    main:                Spec.hs
    source-dirs:         test
    when:
    - condition: false
      other-modules: Paths_turplanering
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - turplanering
    - containers            ^>= 0.6
    - genvalidity           ^>= 0.11
    - genvalidity-hspec     ^>= 0.7
    - genvalidity-text      ^>= 0.7
    - hspec                 ^>= 2.7
    - hspec-expectations    ^>= 0.8
    - optics                ^>= 0.3
    - text                  ^>= 1.2
    - validity              ^>= 0.11
    - validity-text         ^>= 0.3
    - QuickCheck            ^>= 2.14
