on: [push]
name: Srv

defaults:
  run:
    working-directory: srv

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@v2
        - run:  go test -v ./internal/auth
          env:
            LANTMATERIET_CONSUMERID: ${{ secrets.LANTMATERIET_CONSUMERID }}
            LANTMATERIET_CONSUMERKEY: ${{ secrets.LANTMATERIET_CONSUMERKEY }}
