on: [push]
name: Web

defaults:
  run:
    working-directory: web

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
              node-version: '15'
        - run: npm ci
        - run: npm test
        - uses: codecov/codecov-action@v1
          with:
              token: ${{ secrets.CODECOV_TOKEN }}
              file: ./web/coverage/clover.xml
              fail_ci_if_error: true

    lint:
        name: Linter
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
              node-version: '15'
        - run: npm ci
        - run: npm run lint

    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: [tests, lint]
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
              node-version: '15'
        - run: npm ci
        - run: npm run prod -- --public-url .
        - run: npm run docs

        - name: Get short SHA
          id: scratch
          run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

        - name: Deploy
          if: github.ref == 'refs/heads/main'
          uses: peaceiris/actions-gh-pages@v3
          with:
              allow_empty_commit: true
              full_commit_message: ${{ steps.scratch.outputs.sha8 }} ${{ github.event.head_commit.message }}
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./web/dist/
              user_email: "actions@github"
              user_name: "Github Actions"
