on: [push]
name: Web tests

defaults:
  run:
    working-directory: web

jobs:

    build:
        name: Building dist
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
        - run: npm ci
        - run: npm run prod

    tests:
        name: Running tests
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
        - run: npm ci
        - run: npm test

    lint:
        name: Running linter
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
        - run: npm ci
        - run: npm run lint
