on: [push]
name: Web

defaults:
  run:
    working-directory: web

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
              node-version: '14'
        - run: npm ci
        - run: npm test
        - uses: codecov/codecov-action@v1
          with:
              token: ${{ secrets.CODECOV_TOKEN }}
              file: ./web/coverage/clover.xml
              fail_ci_if_error: true

    lint:
        name: Linter
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
              node-version: '14'
        - run: npm ci
        - run: npm run lint

    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: [tests, lint]
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
              node-version: '14'
        - run: npm ci
        - run: npm run prod
        - name: Deploy
          if: github.ref == 'refs/heads/main'
          uses: peaceiris/actions-gh-pages@v3
          with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              commit_message: ${{ github.event.head_commit.message }}
              user_name: "Github Actions"
              user_email: "actions@github"
              publish_dir: ./web/dist/
